[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ct_log"
version = "0.0.1"
description = "Automatic CT Log analysis"
authors = [
  { name = "Marek Provaznik" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.11.0"

[tool.setuptools.packages.find]
where = [".", "thirdparty/MedSAM2", "thirdparty/dinov3"]
include = ["src*", "sam2*", "efficient_track_anything*", "training*", "dinov3*"]
exclude = ["tests*", "notebooks*", "experiments*"]

[tool.ruff]
line-length = 120
src = ["src", "experiments"]
include = ["pyproject.toml", "src/**/*.py", "experiments/**/*.py", "scripts/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["ct_log"]
known-third-party = ["sam2", "dinov3", "efficient_track_anything"]
force-sort-within-sections = true
